export const AUDIENCE = 'https://PORTAFOLIO_API.com';
export const DOMAIN = 'dev-v2roygalmy6qyix2.us.auth0.com';
export const SCOPE = 'offline_access';
export const CLIENT_ID = 'FiGgFZqBNRTXMtroNlRxerrS9FEwWca8';
export const RESPONSE_TYPE = 'code';
// export const REDIRECT_URI = "http://localhost:4200/redirect";
export const REDIRECT_URI = "https://tasty-cliente-staging.web.app/redirect";
// export const API_ENDPOINT = "http://localhost:5221";
export const API_ENDPOINT = "https://tasty-api-staging.onrender.com";