name: "Desplegar api de PROD a Render"
run-name: "Despliegue de la api de PROD a Render. Evento: ${{ github.event_name }} por @${{ github.actor }}"

env:
  BACK_PROJECT_PATH: src/TastysBackend

on:
  push:
    branches:
      - main
    paths:
      - "src/TastysBackend/**"
      - "**/*.md"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Compilar y crear imagen de prod
    defaults:
      run:
        working-directory: ${{ env.BACK_PROJECT_PATH }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.PROD_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PROD_DOCKERHUB_TOKEN }}
      - name: Build y push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BACK_PROJECT_PATH }}
          push: true
          tags: ${{ vars.PROD_BACK_IMAGE_TAG }}
  deploy:
    runs-on: ubuntu-latest
    name: Deploy a Render
    needs: build-and-push
    steps:
      - name: Avisarle a Render que la imagen se ha actualizado.
        run: curl ${{ secrets.PROD_RENDER_DEPLOY_HOOK }}
